"""
generate_modified_idf.py

Reads AI decisions from the SQLite database, calculates the average optimal
cooling and heating setpoints Mistral chose, and writes a new model_modified.idf
that hard-codes those setpoints into the CLGSETP_SCH and HTGSETP_SCH schedules.

This satisfies Hackathon Deliverable #2:
"Building Models: the base baseline file along with modified versions
generated during runtime evaluation."

Run standalone:
    python generate_modified_idf.py

Or call generate_modified_idf() from the API endpoint.
"""

import asyncio
import re
import os
import sys
import logging
import shutil
from pathlib import Path

logger = logging.getLogger(__name__)

BACKEND_DIR = Path(__file__).parent
BASELINE_IDF = BACKEND_DIR / "model.idf"
MODIFIED_IDF = BACKEND_DIR / "model_modified.idf"


async def get_average_ai_setpoints(simulation_id: int = None):
    """Query the DB for the average setpoint and fan_speed from AI decisions."""
    # Add backend to path if running standalone
    if str(BACKEND_DIR) not in sys.path:
        sys.path.insert(0, str(BACKEND_DIR))

    from db.session import AsyncSessionLocal
    from models.ai_decision import AIDecision
    from sqlalchemy import select, func, desc
    from models.simulation import Simulation

    async with AsyncSessionLocal() as db:
        if simulation_id is None:
            # Use the most recent simulation
            result = await db.execute(
                select(Simulation).order_by(desc(Simulation.id)).limit(1)
            )
            sim = result.scalars().first()
            if not sim:
                return None, None
            simulation_id = sim.id

        result = await db.execute(
            select(
                func.avg(AIDecision.setpoint).label("avg_setpoint"),
                func.avg(AIDecision.fan_speed).label("avg_fan_speed"),
                func.count(AIDecision.id).label("count"),
            ).where(AIDecision.simulation_id == simulation_id)
        )
        row = result.first()

        if not row or not row.count:
            return None, None

        avg_setpoint = round(float(row.avg_setpoint), 2) if row.avg_setpoint else None
        avg_fan_speed = round(float(row.avg_fan_speed), 4) if row.avg_fan_speed else None
        decision_count = row.count

        logger.info(
            f"Simulation {simulation_id}: {decision_count} AI decisions — "
            f"avg cooling setpoint={avg_setpoint}°C, avg fan_speed={avg_fan_speed}"
        )
        return avg_setpoint, avg_fan_speed


def patch_idf_schedules(avg_clg_setpoint: float, avg_fan_speed: float) -> str:
    """
    Opens model.idf, patches CLGSETP_SCH and HTGSETP_SCH with the AI's
    average optimal values, and writes model_modified.idf.

    Returns the path to the generated file.
    """
    with open(BASELINE_IDF, "r") as f:
        content = f.read()

    # Calculate heating setpoint from fan_speed proxy
    # fan_speed=1.0 → max heating demand (21°C), fan_speed=0.5 → minimal (15°C)
    if avg_fan_speed is not None:
        htg_setpoint = round(max(15.0, min(21.0, 21.0 * avg_fan_speed)), 2)
    else:
        htg_setpoint = 21.0

    if avg_clg_setpoint is None:
        avg_clg_setpoint = 24.0

    # Patch CLGSETP_SCH — replace all time-of-day values with AI's average
    # The schedule looks like: Until: 06:00,26.7,
    # We replace numeric values (after the comma) with the AI setpoint
    def patch_schedule_block(text: str, schedule_name: str, new_value: float) -> str:
        """Find a Schedule:Compact block by name and patch its numeric values."""
        # Find the schedule block start
        pattern = rf"(Schedule:Compact,\s*\n\s*{re.escape(schedule_name)},.*?;)"
        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
        if not match:
            logger.warning(f"Schedule '{schedule_name}' not found in IDF.")
            return text

        original_block = match.group(1)
        # Replace "Until: HH:MM,<old_value>," with "Until: HH:MM,<new_value>,"
        patched_block = re.sub(
            r"(Until:\s*\d+:\d+,)\s*[\d.]+",
            rf"\g<1>{new_value}",
            original_block
        )
        # Add a comment on the first line identifying this as AI-modified
        patched_block = patched_block.replace(
            f"{schedule_name},",
            f"{schedule_name},  ! AI-Modified: avg={new_value}°C (Mistral autonomous control)",
            1
        )
        return text.replace(original_block, patched_block)

    # Apply patches
    content = patch_schedule_block(content, "CLGSETP_SCH", avg_clg_setpoint)
    content = patch_schedule_block(content, "HTGSETP_SCH", htg_setpoint)

    # Add a header comment at the top of the file
    header_comment = (
        f"! model_modified.idf — AI-Optimized Building Model\n"
        f"! Generated by Honeywell Smart Building AI (Mistral Autonomous Control)\n"
        f"! AI Average Cooling Setpoint: {avg_clg_setpoint}°C\n"
        f"! AI Average Heating Setpoint: {htg_setpoint}°C\n"
        f"! Source baseline: model.idf\n"
        f"!\n"
    )
    content = header_comment + content

    with open(MODIFIED_IDF, "w") as f:
        f.write(content)

    logger.info(f"Saved model_modified.idf → CLG={avg_clg_setpoint}°C, HTG={htg_setpoint}°C")
    return str(MODIFIED_IDF)


async def generate_modified_idf(simulation_id: int = None) -> dict:
    """Main entry point — called by the API endpoint or standalone."""
    avg_clg, avg_fan = await get_average_ai_setpoints(simulation_id)

    if avg_clg is None:
        return {
            "success": False,
            "error": "No AI decisions found in database. Run a simulation first."
        }

    output_path = patch_idf_schedules(avg_clg, avg_fan)
    return {
        "success": True,
        "output_file": output_path,
        "avg_cooling_setpoint_c": avg_clg,
        "avg_fan_speed": avg_fan,
        "message": f"model_modified.idf generated with AI-optimized setpoints (cooling={avg_clg}°C)."
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    result = asyncio.run(generate_modified_idf())
    print(result)
