"""Add decision engine tables

Revision ID: 01dd31734559
Revises: b4d9f22d6dd9
Create Date: 2026-07-25 21:54:27.858595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd31734559'
down_revision: Union[str, Sequence[str], None] = 'b4d9f22d6dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('fan_speed', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_id'), 'ai_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_timestamp'), 'ai_decisions', ['timestamp'], unique=False)
    op.create_table('control_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('fan_speed', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_actions_id'), 'control_actions', ['id'], unique=False)
    op.create_index(op.f('ix_control_actions_timestamp'), 'control_actions', ['timestamp'], unique=False)
    op.create_table('sensor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('indoor_temp', sa.Float(), nullable=True),
    sa.Column('outdoor_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pmv', sa.Float(), nullable=True),
    sa.Column('hvac_energy', sa.Float(), nullable=True),
    sa.Column('cooling_energy', sa.Float(), nullable=True),
    sa.Column('heating_energy', sa.Float(), nullable=True),
    sa.Column('carbon', sa.Float(), nullable=True),
    sa.Column('occupancy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_logs_id'), 'sensor_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_logs_timestamp'), 'sensor_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_logs_timestamp'), table_name='sensor_logs')
    op.drop_index(op.f('ix_sensor_logs_id'), table_name='sensor_logs')
    op.drop_table('sensor_logs')
    op.drop_index(op.f('ix_control_actions_timestamp'), table_name='control_actions')
    op.drop_index(op.f('ix_control_actions_id'), table_name='control_actions')
    op.drop_table('control_actions')
    op.drop_index(op.f('ix_ai_decisions_timestamp'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
